### ISSUE TITLE
Create SauceLabs Jenkins jobs for the coredev builds to test different browsers.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#29] opened 2013-06-23 07:03 UTC
We already created some SauceLabs jobs:

https://jenkins.plone.org/view/All/job/plone-4.3-python-2.7-robot-windows-2003-chrome24/
https://jenkins.plone.org/view/All/job/plone-4.3-python-2.7-robot-windows-2003-ie9/

We had some manually created jobs running at the Barcelona sprint.

@jone @garbas: You worked on that during the sprint, right? Do you have time to make that work again?

**Comment by gforcada** [comment] 2015-04-05 22:37
@datakurre all jobs are currently re-created with jenkins-job-builer but disabled. Should we give them another try or how do you want to move those further (if you want to).

**Comment by datakurre** [comment] 2015-04-06 00:21
How do they currently fail?

Probably Sauce-part should be refactored to be more reusable, but the problem is that it requires to parts:

1. Setup some envs and start Sauce Connect
2. Do stuff (requiring envs from 1.)
3. Kill Sauce Connect

In addition, Sauce Connect has upgraded

https://docs.saucelabs.com/reference/sauce-connect

Now we should download a tarball, extract it and call executable ./sc instead of old jar with Java.

Arguments seem to be the same, but there seems to be an extra requirement of setting unique --se-port for each instance.

Maybe we can fix this together at PLOG? 

Gil Forcada Codinachs kirjoitti ma huhtikuuta 6 01:37:12 2015 GMT+0300:

**Comment by gforcada** [comment] 2015-04-07 07:18
Actually I don't think I ever tried running them, I mostly tried to do a verbatim copy of the previous job configuration, so they should work if they worked before...

@datakurre if you want to work on them let me know so I can help a little bit on the jjb part if you want.

**Comment by gforcada** [comment] 2015-11-29 14:28
@datakurre @tisto is there any interest on keeping them? it's been ~1 year without actually running them...

**Comment by datakurre** [comment] 2015-11-29 16:55
@gforcada I was trying to fix them for themepreview jobs a few months ago, but faced some issue with vagrant setup. I filed an issue for you, but cannot remember anymore where. I should be able to try again soon. Other than themepreview jobs can be scrapped. Once I fix them into themepreview jobs, they can be abstracted there when required.

Gil Forcada Codinachs wrote:

**Comment by gforcada** [comment] 2015-11-29 20:36
@datakurre probably this one: https://github.com/plone/jenkins.plone.org/issues/125 ?

**Comment by datakurre** [comment] 2015-11-29 20:50
@gforcada Thanks. Probably the issue just that. Will try at some point next week :)

Gil Forcada Codinachs wrote:

**Comment by datakurre** [comment] 2015-12-05 11:58
I'm sorry for still failing to do that. This time I failed already in setting up the vagrant environment 
https://github.com/plone/jenkins.plone.org/issues/137

**Comment by gforcada** [comment] 2017-04-21 09:47
@datakurre are you still interested in bringing them back? I fixed the vagrant environment today, please give it a try if you want, or close the issue and we will open a new one whenever the need arises again.

**Closed** 2018-11-10 19:59 UTC
